---
- name: Obter endereço IP e usar no comando curl
  hosts: all
  gather_facts: true

  tasks:
    - name: Obter endereço IP
      set_fact:
        ip_address: "{{ ansible_default_ipv4.address }}"

    - name: Executar comando curl com o endereço IP obtido
      command: curl http://{{ ip_address }}
      register: curl_output

    - name: Exibir saída do comando curl
      debug:
        var: curl_output.stdout
